version: "3"

networks:
  drupal:

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  drupal_db:

services:
  drupal:
    build: .
    networks:
      - drupal
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    ports:
      - "8080:80"
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:5.7
    networks:
      - drupal
    volumes:
      - drupal_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
