apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: quay.io/yuankunzhang/gb:latest
          imagePullPolicy: Always
          ports:
            - name: drupal
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
            periodSeconds: 10
          resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
