apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: quay.io/yuankunzhang/gb:latest
          imagePullPolicy: Always
          ports:
            - name: drupal
              containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: drupal
            - name: DB_USER
              value: drupal
            - name: DB_PASS
              value: changeme
            - name: SITE_NAME
              value: Example
            - name: ACCOUNT_NAME
              value: yuankun
            - name: ACCOUNT_PASS
              value: changeme
          resources:
              limits:
                cpu: 200m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 512Mi
