apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
