version: "3"

networks:
  drupal:

volumes:
  drupal_site:
  drupal_db:

services:
  drupal:
    # image: quay.io/yuankunzhang/gb:latest
    build: ../
    networks:
      - drupal
    volumes:
      - drupal_site:/var/www/html
    environment:
      - DB_HOST=mysql-server
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SITE_NAME=Example
      - ACCOUNT_NAME=yuankun
      - ACCOUNT_PASS=changeme
    ports:
      - "8080:80"
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:5.7
    networks:
      - drupal
    volumes:
      - drupal_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
